routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

// Check name of the route (Giving error)
Route::get('logout', 'LoginController@logout')->name('logout');
Route::resource('login', 'LoginController');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});

app/Models/Post.php
<?php
/**
 * Created by PhpStorm.
 * User: rv
 * Date: 23/07/17
 * Time: 6:39 PM
 */

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

class Post extends Eloquent {

     use SoftDeletes;

     protected $connection = 'mongodb';

     protected $fillable = ['title', 'slug', 'is_published', 'body', 'user_id', 'category_id'];
     protected $dates = ['deleted_at'];

     public function user()
     {
         return $this->belongsTo(User::class);
     }

     public function category()
     {
        return $this->belongsTo(Category::class);
     }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Http\Requests\Post as PostValidator;
use App\Repositories\CategoryRepository;
use App\Repositories\PostRepository;

class PostController extends Controller
{
    const SINGULAR = 'post';
    const PLURAL = 'posts';

    private $categoriesRepository;

    /**
     * Create a new post controller instance.
     *
     * @param  PostRepository  posts
     * @return void
     */
    public function __construct(PostRepository $posts, CategoryRepository $categories)
    {
        $this->repository = $posts;
        $this->categoriesRepository = $categories;
    }

    public function create()
    {
        return parent::create()
            ->with([
                'categories' => $this->categoriesRepository->all()
            ]);
    }

    public function show(Post $post)
    {
        return parent::afterShow($post);
    }

    public function update(PostValidator $request, Post $post)
    {
        return parent::afterUpdate($request, $post);
    }

    public function store(PostValidator $request)
    {
        return parent::afterStore($request);
    }

    public function destroy(Post $post)
    {
        return parent::afterDestroy($post);
    }
}

resources/views/post/create.blade.php
@extends('layouts.base')

@section('title', 'Post')

@section('subtitle', 'create')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <br />
                    <form method="POST" action="{{ route('posts.store') }}" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        @include('layouts.message')
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Title <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="title" name="title" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="category">Category <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select class="form-control col-md-7 col-xs-12" id="category_id" name="category_id">
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="slug">Slug
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="slug" name="slug" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Published</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="gender" class="btn-group" data-toggle="buttons">
                                        <input type="radio" name="is_published" value="1" checked="checked"> &nbsp; Yes &nbsp;
                                        <input type="radio" name="is_published" value="0"> &nbsp; No &nbsp;
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Body <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="body" name="body" class="date-picker form-control col-md-7 col-xs-12" required="required"></textarea>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('posts.index') }}" class="btn btn-primary" type="button">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.base')

@section('title', 'Post')

@section('subtitle', 'All')

@section('content')
    <div class="text-center">
        <a class="btn btn-primary" href="{{ route('posts.create') }}">Create new article</a>
    </div>

    @if(count($posts))
    <!-- start project list -->
    <table class="table table-striped projects">
        <thead>
            <tr>
                <th style="width: 20%">Title</th>
                <th>Slug</th>
                <th>Body</th>
                <th>Author</th>
                <th>Category</th>
                <th>Status</th>
                <th style="width: 20%">#Edit</th>
            </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
        <tr>
            <td>
                {{ $post->title }}
            </td>
            <td>
                {{ $post->slug }}
            </td>
            <td>
                {{ str_limit($post->body, $limit = 30, $end = '...') }}
            </td>
            <td>
                {{ $post->user->name }}
            </td>
            <td>
                {{ $post->category->name }}
            </td>
            <td>
                <button type="button" class="btn btn-{{ $post->is_published ? 'success' : 'warning'}} btn-xs">{{ $post->is_published ? 'Published' : 'Unpublished'}}</button>
            </td>
            <td>
                <form method="POST" action="{{ route('posts.destroy', ['post' => $post->id]) }}">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <a href="{{ route('posts.show', ['post' => $post->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    <!-- end project list -->
    @else
        <div class="text-center" style="margin-top: 30px">
            <strong>There isn't post yet!</strong>
        </div>
    @endif
@endsection

resources/views/post/show.blade.php
@extends('layouts.base')

@section('title', 'Post')

@section('subtitle', 'create')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <br />
                    <form method="POST" action="{{ route('posts.update', ['post' => $post->id]) }}" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        @include('layouts.message')
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Title <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="title" name="title" required="required" class="form-control col-md-7 col-xs-12" value="{{ $post->title }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="slug">Slug
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="slug" name="slug" class="form-control col-md-7 col-xs-12" value="{{ $post->slug }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Published</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="gender" class="btn-group" data-toggle="buttons">
                                        <input type="radio" name="is_published" value="1" {{ $post->is_published ? 'checked="checked"' : '' }}> &nbsp; Yes &nbsp;
                                        <input type="radio" name="is_published" value="0" {{ !$post->is_published ? 'checked="checked"' : '' }}> &nbsp; No &nbsp;
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Body <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="body" name="body" class="date-picker form-control col-md-7 col-xs-12" required="required">{{ $post->body }}</textarea>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('posts.index') }}" class="btn btn-primary" type="button">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection