routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

// Check name of the route (Giving error)
Route::get('logout', 'LoginController@logout')->name('logout');
Route::resource('login', 'LoginController');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});

app/Models/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: rv
 * Date: 23/07/17
 * Time: 6:39 PM
 */

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

class Category extends Eloquent {

     use SoftDeletes;

     protected $connection = 'mongodb';

     protected $fillable = ['name'];
     protected $dates = ['deleted_at'];

    public function posts()
    {
        return $this->embedsMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Http\Requests\Category as CategoryValidator;
use App\Repositories\CategoryRepository;

class CategoryController extends Controller
{
    const SINGULAR = 'category';
    const PLURAL = 'categories';

    /**
     * Create a new category controller instance.
     *
     * @param  CategoryRepository  categories
     * @return void
     */
    public function __construct(CategoryRepository $categories)
    {
        $this->repository = $categories;
    }

    public function show(Category $category)
    {
        return parent::afterShow($category);
    }

    public function update(CategoryValidator $request, Category $category)
    {
        return parent::afterUpdate($request, $category);
    }

    public function store(CategoryValidator $request)
    {
        return parent::afterStore($request);
    }

    public function destroy(Category $category)
    {
        return parent::afterDestroy($category);
    }
}

resources/views/category/create.blade.php
@extends('layouts.base')

@section('title', 'Category')

@section('subtitle', 'create')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <br />
                    <form method="POST" action="{{ route('categories.store') }}" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        @include('layouts.message')
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="name" name="name" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('categories.index') }}" class="btn btn-primary" type="button">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.base')

@section('title', 'Category')

@section('subtitle', 'All')

@section('content')
    <div class="text-center">
        <a class="btn btn-primary" href="{{ route('categories.create') }}">Create new category</a>
    </div>

    @if(count($categories))
    <!-- start project list -->
    <table class="table table-striped projects">
        <thead>
            <tr>
                <th style="width: 20%">Name</th>
                <th style="width: 20%">#Edit</th>
            </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
        <tr>
            <td>
                {{ $category->name }}
            </td>
            <td>
                <form method="POST" action="{{ route('categories.destroy', ['category' => $category->id]) }}">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <a href="{{ route('categories.show', ['category' => $category->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    <!-- end project list -->
    @else
        <div class="text-center" style="margin-top: 30px">
            <strong>There isn't categories yet!</strong>
        </div>
    @endif
@endsection

resources/views/category/show.blade.php
@extends('layouts.base')

@section('title', 'Category')

@section('subtitle', 'create')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <br />
                    <form method="POST" action="{{ route('categories.update', ['category' => $category->id]) }}" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        @include('layouts.message')
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="name" name="name" required="required" class="form-control col-md-7 col-xs-12" value="{{ $category->name }}">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('categories.index') }}" class="btn btn-primary" type="button">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection